language: csharp
install:
  - sudo apt-get install nunit-console
  - nuget restore ./OrderedJobs.sln

script:
  - xbuild ./OrderedJobs.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.5 /toolsversion:12.0
  - nunit-console ./OrderedJobs.Tests/bin/Release/OrderedJobs.Tests.dll
